# Generated by Django 3.0.7 on 2020-07-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='phoneNo',
        ),
    ]
